# Optional helper kept for presets; main logic is in CMakeLists.txt
function(toughnessfeast_resolve_kenshilib)
  set(_bundled "${CMAKE_SOURCE_DIR}/third_party/KenshiLib")
  if(DEFINED KENSHILIB_DIR AND NOT KENSHILIB_DIR STREQUAL "")
    file(TO_CMAKE_PATH "${KENSHILIB_DIR}" KENSHILIB_DIR)
  elseif(DEFINED ENV{KENSHILIB_DIR} AND NOT "$ENV{KENSHILIB_DIR}" STREQUAL "")
    file(TO_CMAKE_PATH "$ENV{KENSHILIB_DIR}" KENSHILIB_DIR)
  elseif(EXISTS "${_bundled}/Include/Debug.h")
    set(KENSHILIB_DIR "${_bundled}")
  else()
    set(KENSHILIB_DIR "")
  endif()
  set(KENSHILIB_DIR "${KENSHILIB_DIR}" PARENT_SCOPE)
endfunction()
